# Generated by Django 4.0.6 on 2022-07-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNumber', models.CharField(max_length=50)),
                ('IsDeleted', models.BooleanField(default=True)),
                ('CreateAt', models.DateField()),
                ('ModifiedAt', models.DateField()),
                ('DeletedAt', models.DateField()),
                ('InvoiceDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'tax',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeP', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=50)),
                ('Quality', models.IntegerField()),
                ('PriceP', models.IntegerField()),
                ('CostP', models.IntegerField()),
                ('UnitP', models.CharField(max_length=50)),
                ('Precentage', models.IntegerField()),
                ('PencetagePrice', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('InvoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.invoice')),
            ],
            options={
                'verbose_name': 'InvoiceDetails',
                'verbose_name_plural': 'InvoiceDetails',
            },
        ),
    ]
