# Generated by Django 4.0.6 on 2022-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_invoice_options_alter_invoicedetails_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='IsDeleted',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='CodeP',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='CostP',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='PriceP',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='Quality',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='UnitP',
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='CodeProduct',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='CostProduct',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='PriceProduct',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='UnitProduct',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='quantity',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Desc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Precentage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='PrecentagePrice',
            field=models.IntegerField(),
        ),
    ]
