# Generated by Django 4.0.6 on 2022-07-29 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0003_alter_bussines_options'),
        ('Sales', '0005_alter_invoice_createat_alter_invoice_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='CreatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_CreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='DeleteBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_DeleteBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='EnterpriceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.bussines'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ModifiyBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_ModifiyBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='TaxId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.tax'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='CodeProduct',
            field=models.CharField(default=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='InvoiceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Precentage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='PrecentagePrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='Total',
            field=models.IntegerField(null=True),
        ),
    ]
