# Generated by Django 4.0.6 on 2022-07-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameCategory', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeP', models.CharField(max_length=50)),
                ('NameP', models.CharField(max_length=50)),
                ('AmoutMin', models.IntegerField()),
                ('AmountMax', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('IsDeleted', models.BooleanField(default=True)),
                ('CreateAt', models.DateField()),
                ('ModifiedAt', models.DateField()),
                ('DeletedAt', models.DateField()),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.categoryproduct')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
