# Generated by Django 4.0.6 on 2022-07-22 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_CreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='DeleteBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_DeleteBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='ModifiyBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_ModifiyBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='Taxid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.tax'),
        ),
    ]
