# Generated by Django 4.0.6 on 2022-07-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_invoice_options_alter_invoicedetails_options_and_more'),
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='NameCategory',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='AmountMax',
            field=models.IntegerField(verbose_name='Cantidad Maxima'),
        ),
        migrations.AlterField(
            model_name='product',
            name='AmoutMin',
            field=models.IntegerField(verbose_name='Cantidad Minima'),
        ),
        migrations.AlterField(
            model_name='product',
            name='CategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.categoryproduct', verbose_name='Categoria del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='CodeP',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost',
            field=models.IntegerField(verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='CreateAt',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='DeletedAt',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ModifiedAt',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='NameP',
            field=models.CharField(max_length=50, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Taxid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.tax', verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
