# Generated by Django 4.0.6 on 2022-07-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0004_rename_isdeleted_invoice_state_and_more'),
        ('Product', '0003_alter_categoryproduct_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='IsDeleted',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CodeP',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='NameP',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
        migrations.AddField(
            model_name='product',
            name='CodeProduct',
            field=models.CharField(default='0', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='CostProduct',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='NameProduct',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PriceProduct',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='AmountMax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='AmoutMin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='CategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.categoryproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='CreatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_CreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='DeleteBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_DeleteBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='ModifiyBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_ModifiyBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='Taxid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.tax'),
        ),
    ]
