# Generated by Django 4.0.6 on 2022-07-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rename_isdeleted_product_state_remove_product_codep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreateAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='DeletedAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ModifiedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
