# Generated by Django 4.0.6 on 2022-07-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_invoice_createat_alter_invoice_deletedat_and_more'),
        ('Product', '0005_alter_product_createat_alter_product_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AmountMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='AmoutMin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='CategoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.categoryproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Taxid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.tax'),
        ),
    ]
