# Generated by Django 4.0.6 on 2022-07-22 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
        ('PushCase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushcase',
            name='CreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pushcase_CreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushcase',
            name='DeleteBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pushcase_DeleteBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushcase',
            name='EnterpriceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.bussines'),
        ),
        migrations.AddField(
            model_name='pushcase',
            name='ModifiyBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pushcase_ModifiyBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
