# Generated by Django 4.0.6 on 2022-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PushCase', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushcase',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='pushcasedetail',
            options={'verbose_name': 'Dedatalle de compra', 'verbose_name_plural': 'Detalles de compras'},
        ),
        migrations.RemoveField(
            model_name='pushcasedetail',
            name='PencetagePrice',
        ),
        migrations.AddField(
            model_name='pushcasedetail',
            name='PrecentagePrice',
            field=models.IntegerField(default=0, verbose_name='Precio Porcentual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='CreateAt',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='DeletedAt',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='ModifiedAt',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='PushcaseDate',
            field=models.DateField(verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='PushcaseNumeber',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numero de Compra'),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='CodeP',
            field=models.CharField(max_length=50, verbose_name='codigo del producto'),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='CostP',
            field=models.IntegerField(verbose_name='Costo del Producto'),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='Desc',
            field=models.CharField(max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='Precentage',
            field=models.IntegerField(verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='PriceP',
            field=models.IntegerField(verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='Quality',
            field=models.IntegerField(verbose_name='Calidad'),
        ),
    ]
