# Generated by Django 4.0.6 on 2022-07-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PushCase', '0003_alter_pushcase_options_alter_pushcasedetail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushcase',
            old_name='IsDeleted',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='pushcasedetail',
            name='CodeP',
        ),
        migrations.RemoveField(
            model_name='pushcasedetail',
            name='CostP',
        ),
        migrations.RemoveField(
            model_name='pushcasedetail',
            name='PriceP',
        ),
        migrations.RemoveField(
            model_name='pushcasedetail',
            name='Quality',
        ),
        migrations.RemoveField(
            model_name='pushcasedetail',
            name='UnitP',
        ),
        migrations.AddField(
            model_name='pushcasedetail',
            name='CodeProduct',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='pushcasedetail',
            name='CostProduct',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pushcasedetail',
            name='PriceProduct',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pushcasedetail',
            name='UnitProduct',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pushcasedetail',
            name='quantity',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='CreatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pushcase_CreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='DeleteBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pushcase_DeleteBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='ModifiyBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pushcase_ModifiyBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='PushcaseDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='PushcaseNumeber',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='Desc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='Precentage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='PrecentagePrice',
            field=models.IntegerField(),
        ),
    ]
