# Generated by Django 4.0.6 on 2022-07-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_bussines_options'),
        ('PushCase', '0005_alter_pushcase_createat_alter_pushcase_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushcase',
            name='EnterpriceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.bussines'),
        ),
        migrations.AlterField(
            model_name='pushcase',
            name='PushcaseDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='CodeProduct',
            field=models.CharField(default=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='Precentage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='PrecentagePrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pushcasedetail',
            name='Total',
            field=models.IntegerField(null=True),
        ),
    ]
