# Generated by Django 4.0.6 on 2022-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='IsDeleted',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Quality',
            field=models.IntegerField(verbose_name='Calidad'),
        ),
    ]
