# Generated by Django 4.0.6 on 2022-07-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0003_alter_inventory_options_alter_inventory_isdeleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='IsDeleted',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Quality',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='CreatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_CreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='DeleteBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_DeleteBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ModifiyBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_ModifiyBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
