# Generated by Django 4.0.6 on 2022-07-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_createat_alter_product_deletedat_and_more'),
        ('Inventory', '0004_remove_inventory_isdeleted_remove_inventory_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ProductId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='state',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
